c/cpp:
  - "**/*.c"
  - "**/*.cpp"
  - "**/*.h"
  - "**/*.hpp"

docs:
  - "**/*.md"

ci:
  - ".github/**"

js/ts:
  - "**/*.js"
  - "**/*.jsx"
  - "**/*.ts"
  - "**/*.tsx"
  - "vite.config.*"       # Vite config files
  - "vite.*.js"          # optional extra patterns
  - "package.json"       # package manifest changes
  - "package-lock.json"
  - "yarn.lock"
