services:
  dev:
    image: ${IMG2NUM_IMAGE:-ryanmillard/img2num-dev:latest} # Allow specifying the image
    environment:
      IMG2NUM_IMAGE: ${IMG2NUM_IMAGE:-ryanmillard/img2num-dev:latest}
    pull_policy: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app:cached
      - pnpm-store:/pnpm
    ports:
      - "5173:5173" # Vite dev
      - "4173:4173" # Vite preview
      - "3000:3000" # Docusaurus dev
    stdin_open: true
    tty: true

volumes:
  pnpm-store:
