packages:
  - packages/js
  - example-apps/react-js
  - example-apps/console-js-cjs
  - example-apps/console-js-esm
  - example-apps/html-js
  - example-apps/html-js-iife
  - example-apps/html-js-umd
  - docs
  - scripts/img2num-dev-scripts

allowBuilds:
  "@swc/core": true
  core-js: true
  sharp: true
  webgpu: true

minimumReleaseAgeExclude:
  - lucide-react@1.22.0

onlyBuiltDependencies:
  - "@swc/core"
  - core-js
  - core-js-pure
  - esbuild
  - sharp
  - webgpu
