name: Bug Report
description: Report a bug
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to explain the issue you have discovered.

  - type: checkboxes
    id: languages
    attributes:
      label: Affected languages
      options:
        - label: C++
        - label: C
        - label: JavaScript
        - label: Python
        - label: Other
        - label: N/A
    validations:
      required: true

  - type: textarea
    id: other_platform
    attributes:
      label: If you selected "Other", please specify which language.
      placeholder: Tell us what "Other" refers to
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      placeholder: |
        Example: when I blur the image, my app crashes.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        Example:
        1. Load image using STB
        2. Threshold to 4 colors
        3. Run K-Means
        4. Crash before K-Means ends
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What was the expected result?
      placeholder: |
        Example: I expected K-Means to complete segmentation successfully.

  - type: textarea
    id: screenshots
    attributes:
      label:  |
        Please include some screenshots here if necessary.
        The more information we have, the better-equipped we will be to resolve this issue.

  - type: dropdown
    id: assign
    attributes:
      label: "Would you like to work on this issue?"
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! We will get back to you as soon as possible.
