import sys, pathlib

SHADER_DIR = pathlib.Path(sys.argv[1])
OUTPUT_FILE = pathlib.Path(sys.argv[2])

# Must always appear in the same order for predictability
files = sorted(SHADER_DIR.glob("*.wgsl"))

shader_strings = ""
shader_array_contents = ""
for file in files:
    name = file.stem
    text = file.read_text()

    shader_strings += f'    constexpr char {name}[] = R"WGSL(\n{text}\n)WGSL";\n\n'
    shader_array_contents += f'        {{"{name}", {name}}},\n'

# We need to use {{ and }} to escape the f-string expansion
file_contents = f"""// Do not edit this file
// core/tools/embed_shaders.py manages the contents of this file

#ifndef EMBEDDED_SHADERS_H
#define EMBEDDED_SHADERS_H

#include <array>
#include <string_view>
#include <string>

namespace embedded_shaders {{
    struct ShaderEntry {{
      const std::string_view id;
      const std::string_view source;
    }};

{shader_strings}

    constexpr std::array<ShaderEntry, {len(files)}> shaders = {{{{
{shader_array_contents}
    }}}};
}}  // namespace embedded_shaders

#endif // EMBEDDED_SHADERS_H
"""

# Only write if the file doesn't exist or contents differ
if not OUTPUT_FILE.exists() or OUTPUT_FILE.read_text() != file_contents:
    OUTPUT_FILE.write_text(file_contents)
    print(f"Writing to {OUTPUT_FILE}")
else:
    print(f"No changes in {OUTPUT_FILE}, skipping write")
