import sys
import pathlib

# Hard-coded expected locations (build purity guarantee)
EXPECTED_SHADER_DIR = pathlib.Path("../../core/src/internal/resources").resolve()
EXPECTED_OUTPUT_FILE = pathlib.Path("../core/generated/embedded_shaders.h").resolve()

# Inputs
if len(sys.argv) != 3:
    raise ValueError("Usage: embed_shaders.py <shader_dir> <output_file>")
SHADER_DIR = pathlib.Path(sys.argv[1]).resolve()
OUTPUT_FILE = pathlib.Path(sys.argv[2]).resolve()

# Strict validation (your original safety model)
if SHADER_DIR != EXPECTED_SHADER_DIR:
    raise ValueError(
        "CMake embed_shaders.py SHADER_DIR argument is incorrect:\n"
        f"  Expected: {EXPECTED_SHADER_DIR}\n"
        f"  Got:      {SHADER_DIR}"
    )

if OUTPUT_FILE != EXPECTED_OUTPUT_FILE:
    raise ValueError(
        "CMake embed_shaders.py OUTPUT_FILE argument is incorrect:\n"
        f"  Expected: {EXPECTED_OUTPUT_FILE}\n"
        f"  Got:      {OUTPUT_FILE}"
    )

# Only use trusted, hard-coded paths for filesystem operations
SHADER_DIR = EXPECTED_SHADER_DIR
OUTPUT_FILE = EXPECTED_OUTPUT_FILE

# Collect shaders (deterministic)
files = sorted(SHADER_DIR.glob("*.wgsl"))
if not files:
    raise ValueError(f"No .wgsl files found in expected directory: {SHADER_DIR}")

# Generate output
shader_blocks = []
shader_array_contents = []
for file in files:
    name = file.stem
    text = file.read_text(encoding="utf-8")

    shader_blocks.append(
        f'    constexpr char {name}[] = R"WGSL(\n{text}\n)WGSL";'
    )

    shader_array_contents.append(
        f'        {{"{name}", {name}}},'
    )

shader_strings = "\n\n".join(shader_blocks)
shader_array_contents = "\n".join(shader_array_contents)

file_contents = f"""// Do not edit this file
// core/tools/embed_shaders.py manages the contents of this file

#ifndef EMBEDDED_SHADERS_H
#define EMBEDDED_SHADERS_H

#include <array>
#include <string_view>
#include <string>

namespace embedded_shaders {{
    struct ShaderEntry {{
      const std::string_view id;
      const std::string_view source;
    }};

{shader_strings}

    constexpr std::array<ShaderEntry, {len(files)}> shaders = {{{{
{shader_array_contents}
    }}}};
}}  // namespace embedded_shaders

#endif // EMBEDDED_SHADERS_H
"""

# Write only if changed
if not OUTPUT_FILE.exists() or OUTPUT_FILE.read_text(encoding="utf-8") != file_contents:
    OUTPUT_FILE.write_text(file_contents, encoding="utf-8")
    print(f"Writing to {OUTPUT_FILE}")
else:
    print(f"No changes in {OUTPUT_FILE}, skipping write")
