name: Check Spelling

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "**"

permissions:
  contents: read
  pull-requests: read

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Run check-spelling
        uses: check-spelling/check-spelling@cfb6f7e75bbfc89c71eaa30366d0c166f1bd9c8c # v0.0.26
        with:
          config: .github/.check-spelling
          suppress_push_for_open_pull_request: true
          quit_without_error: true
