name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: Lint & Validate Code
    runs-on: ubuntu-latest
    container:
      image: >-
        ${{
          github.event_name == 'pull_request'
          && format('ryanmillard/img2num-dev:pr-{0}', github.event.pull_request.number)
          || 'ryanmillard/img2num-dev:main/g'
        }}

    steps:
      - name: Checkout code
        # No need for submodules since we are not running code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install PNPM dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run eslint

      - name: Validate format
        run: pnpm run format:check

      - name: Validate .editorconfig adherance
        run: pnpm run editorconfig:check

      - name: Validate scriptsInfo in package.json
        run: pnpm run validate-scripts

  cmake-build:
    name: Build C/C++
    uses: ./.github/workflows/cmake-build.yml
    with:
      image: >-
        ${{
          github.event_name == 'pull_request'
          && format('ryanmillard/img2num-dev:pr-{0}', github.event.pull_request.number)
          || 'ryanmillard/img2num-dev:main/g'
        }}

  build-react-app:
    name: Build React App
    uses: ./.github/workflows/build-react-app.yml
    needs: cmake-build
    with:
      image: >-
        ${{
          github.event_name == 'pull_request'
          && format('ryanmillard/img2num-dev:pr-{0}', github.event.pull_request.number)
          || 'ryanmillard/img2num-dev:main/g'
        }}
      wasm-artifacts-path: packages/js/build-wasm/

  build-docs:
    name: Build Documentation Site
    uses: ./.github/workflows/build-docs.yml
    with:
      image: >-
        ${{
          github.event_name == 'pull_request'
          && format('ryanmillard/img2num-dev:pr-{0}', github.event.pull_request.number)
          || 'ryanmillard/img2num-dev:main/g'
        }}
    secrets:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
