name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  packages: read

jobs:
  set-image:
    name: Set Docker image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set.outputs.image }}
    steps:
      - name: Set image
        id: set
        run: |
          MAIN_IMAGE="ghcr.io/ryan-millard/img2num-dev:main"
          PR_TAG="pr-${{ github.event.pull_request.number }}"
          REPO="ryan-millard/img2num-dev"
          DH_IMAGE="${REPO}:${PR_TAG}"
          GHCR_IMAGE="ghcr.io/${DH_IMAGE}"
          GHCR_IMAGE_CACHE="ghcr.io/${REPO}:cache-${PR_TAG}"

          GHCR_TOKEN="$(curl "https://ghcr.io/token?scope=repository:ryan-millard/img2num-dev:pull" | awk -F'"' '$0=$4')"

          GHCR_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${GHCR_TOKEN}" \
            -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/ryan-millard/img2num-dev/manifests/${PR_TAG}")

          GHCR_CACHE_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: Bearer ${GHCR_TOKEN}" \
            -H "Accept: application/vnd.oci.image.index.v1+json,application/vnd.docker.distribution.manifest.v2+json" \
            "https://ghcr.io/v2/ryan-millard/img2num-dev/manifests/cache-${PR_TAG}")

          echo "ghcr_status=${GHCR_STATUS}"
          echp "ghcr_cache_status=${GHCR_CACHE_STATUS}"

          DH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            "https://registry.hub.docker.com/v2/repositories/${REPO}/tags/${PR_TAG}/")

          if [[ "$GHCR_STATUS" == "200" ]]; then
            echo "image=${GHCR_IMAGE}"
            echo "image=${GHCR_IMAGE}" >> $GITHUB_OUTPUT
          elif [[ "$GHCR_CACHE_STATUS" == "200" ]]; then
            echo "image=${GHCR_IMAGE_CACHE}"
            echo "image=${GHCR_IMAGE_CACHE}" >> $GITHUB_OUTPUT
          elif [[ "$DH_STATUS" == "200" ]]; then
            echo "image=${DH_IMAGE}"
            echo "image=${DH_IMAGE}" >> $GITHUB_OUTPUT
          else
            echo "image=${MAIN_IMAGE}"
            echo "image=${MAIN_IMAGE}" >> $GITHUB_OUTPUT
          fi

  lint:
    name: Lint & Validate Code
    needs: [set-image]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.set-image.outputs.image }}
    steps:
      - name: Checkout code
        # No need for submodules since we are not running code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install PNPM dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run eslint

      - name: Validate format
        run: pnpm run format:check

      - name: Validate .editorconfig adherance
        run: pnpm run editorconfig:check

      - name: Validate scriptsInfo in package.json
        run: pnpm run validate-scripts

  cmake-build:
    name: Build C/C++
    uses: ./.github/workflows/cmake-build.yml
    needs: [set-image]
    with:
      image: ${{ needs.set-image.outputs.image }}

  build-react-app:
    name: Build React App
    uses: ./.github/workflows/build-react-app.yml
    needs: [set-image, cmake-build]
    with:
      image: ${{ needs.set-image.outputs.image }}
      wasm-artifacts-path: packages/js/build-wasm/

  build-docs:
    name: Build Documentation Site
    uses: ./.github/workflows/build-docs.yml
    needs: [set-image]
    with:
      image: ${{ needs.set-image.outputs.image }}
    secrets:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
