name: Build C & C++

on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
        description: "The name of the GitHub artifact containing the docker image tarball."

permissions:
  contents: read

jobs:
  build-wasm:
    name: Build WASM (bindings/js)
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: /tmp

      - name: Load Docker Image
        run: |
          docker load --input /tmp/image.tar
          # Verify the image is loaded (it will be tagged as local-image:latest per the build-docker script)
          docker image ls

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true

      - name: Run emcmake
        run: emcmake cmake -DCMAKE_BUILD_TYPE=Release -B build-wasm/ .

      - name: Build using Emscripten
        run: cmake --build build-wasm/

      - name: Upload WASM build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: wasm-build
          path: packages/js/build-wasm/

  build-c-cpp:
    name: Build C & C++
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: /tmp
          
      - name: Load Docker Image
        run: |
          docker load --input /tmp/image.tar
          # Verify the image is loaded (it will be tagged as local-image:latest per the build-docker script)
          docker image ls
          
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          submodules: true

      - name: Check toolchain
        run: |
          cmake --version
          clang --version

      - name: Run cmake
        run: cmake -B build-c-cpp/ .

      - name: Build C/C++
        run: cmake --build build-c-cpp/

      - name: Upload C/C++ build artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: build-c-cpp
          path: build-c-cpp/
