name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  image: ryanmillard/img2num-dev:main

jobs:
  wait-for-image:
    name: Wait for Docker image to be pushed to Docker Hub
    uses: ./.github/workflows/wait-for-docker-image.yml

  cmake-build:
    name: Build WASM
    needs: wait-for-image
    uses: ./.github/workflows/cmake-build.yml
    with:
      image: ${{ env.image }}

  build-react-app:
    name: Build React App
    uses: ./.github/workflows/build-react-app.yml
    needs: [cmake-build, wait-for-image]
    with:
      wasm-artifacts-path: packages/js/build-wasm/
      image: ${{ env.image }}

  build-docs:
    name: Build Documentation Site
    needs: wait-for-image
    uses: ./.github/workflows/build-docs.yml
    with:
      image: ${{ env.image }}
    secrets:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}

  deploy:
    name: Deploy site to GH Pages
    needs: [build-react-app, build-docs, wait-for-image]
    runs-on: ubuntu-latest
    steps:
      - name: Download React build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: react-build
          path: ./new-react-build

      - name: Download Docs build artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: docs-build
          path: ./new-docs-build

      - name: Prepare built assets
        run: |
          mkdir -p ./new-build/info
          # We could just mv, but cp keeps the structure and works like a log for debugging if necessary
          cp -r ./new-react-build/* ./new-build
          cp -r ./new-docs-build/* ./new-build/info

      - name: Deploy React App
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./new-build
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"

      - name: Clean temp folders
        run: rm -rf ./new-react-build ./new-docs-build
