name: Publish wiki
on:
  push:
    branches: [ main ]
    paths:
      - 'wiki/**'

permissions:
  contents: write

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    concurrency:
      group: publish-wiki
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          strategy: init
          path: wiki
          commit-message: "Sync wiki from /wiki"
